### ISSUE TITLE
Informacja

### ISSUE THREAD

**Issue by PGrochowalski** [Helowith/BD_2020_Helowicz_Damian#1]
W ramach przygotowanego projektu bazy danych proszę przygotować poprawny diagram ERD. Jakie funkcjonalności, analizy przewiduje Pan w ramach projektu bazujące na SQL, aby można je było wesprzeć możliwościami programistycznymi PLSQL'a.

**Comment by Helowith** [comment]
Dzień dobry, 
postanowiłem zmienić koncepcję projektu na nieco prostszą do zrealizowania - wypożyczalnię samochodów (repozytorium jest uaktualnione o konkretne informacje tj. schemat ERD oraz informacje w opisie/założeniach). Poprzedni projekt stał się zbyt rozległy jak na jedną osobę oraz nie miałem konkretnych pomysłów, co mógłbym zrobić w PL/SQLu. Tutaj zastosowałem 5 tabel głównych. Dodałem wstępne informacje, co chciałbym zrobić w tym projekcie wykorzystując język PL/SQL (dopiero sprawdzam, jakie możliwości on posiada, dlatego nie jestem w stanie na ten moment powiedzieć, czy to wszystko, co w nim zrobię). 
Pozdrawiam 
Damian Helowicz

**Comment by PGrochowalski** [comment]
Dzień dobry
Wprowadzona zmiana, skutkuje tym, że rozważany projekt był już wybierany przez różne osoby i  proszę zastanowić się nad jakimiś własnymi modyfikacjami. Dodatkowo przygotowany diagram nie jest poprawnym diagramem ERD, czemu tabela pracownicy nie jest z nikim związana.

**Comment by Helowith** [comment]
Dzień dobry, 
nieco zmodyfikowałem schemat bazy(dodałem np. status wypożyczenia w tabeli wypożyczeń). Pracownik został przypisany do miejsca i to on będzie miał widok na zamówienie (on będzie administratorem). W tym miejscu proszę też o informację, czy pracownika(jako tego zarządzającego) zostawić w tej formie, czy umieścić go w odłączonej tabeli, bez relacji. Szukałem już w różnych źródłach i uzyskuję sprzeczne informacje w tym temacie, dlatego też proszę o Pana sugestię. Więcej modyfikacji (jeśli będą konieczne) będę starał się dodawać w trakcie. Starałem się, aby ten schemat był już jak najbardziej kompletny, dlatego też w razie czego, bardzo proszę o informację, co konkretnie poprawić/dodać/usunąć, ponieważ czasu jest już coraz mniej, a chciałbym zacząć robić coś więcej. Z góry dziękuję za pomoc. 
Pozdrawiam 
Damian Helowicz

**Comment by PGrochowalski** [comment]
Dzień dobry,
W odniesieniu do pracownika to jeżeli ma mieć on coś wspólnego z zamówieniem to musi zostać z nim powiązany, czyli tak jak jest teraz. Zlikwidowanie tego powiązania, skutkowałoby tym, że nie dało by się określić, który z pracowników zajmuje się danym zamówieniem.
W kwestii dalszych prac związanych z projektem to proszę działać dalej, ale mieć na uwadze modyfikacje o których pisałem wcześniej.

**Comment by PGrochowalski** [comment]
Dzień dobry,
Aktualnie w kwestii kontaktu zgodnie z wytycznymi uczelni przechodzimy na MS Teams. Proszę się zalogować w MS Teams minimalnie do moich przedmiotów, tam również znajdują się zdania do wykonania, jedno z nich jest teraz aktualne i ograniczone czasowo. 
Proszę również zgodnie z tymi wytycznymi zmienić typ repozytorium na prywatny.
